services:
  decidim:
    container_name: decidim
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - bundle-dev:/home/decidim/app/vendor
      - .:/home/decidim/app
    environment:
      DECIDIM_SYSTEM_EMAIL: "hello@myorg.com"
      DECIDIM_SYSTEM_PASSWORD: "my_insecure_password"
      DATABASE_URL: "postgres://decidim:my_insecure_password@pg_dev:5432/decidim"
      REDIS_URL: "redis://default:my_insecure_password@redis:6379/1"
      PM2_RUN: decidim
      QUEUE_ADAPTER: async
    links:
      - pg_dev
    networks:
      - private
      - default

  pg_dev:
    image: postgres:15-alpine
    volumes:
      - pg-data-dev:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "my_insecure_password"
      POSTGRES_USER: "decidim"
      POSTGRES_DB: "decidim"
    networks:
      - private


volumes:
  pg-data-dev: {}
  bundle-dev: {}

networks:
  private: