FROM hfroger/decidim:0.27-dev
ENV RAILS_ENV=development \
    NODE_ENV=development \
    ROOT=/home/decidim/app
COPY . $ROOT

RUN cd $ROOT \ 
  && bundle config set without "" \
  && bundle config set path "vendor" \
  && bundle install \
  && npm install -D webpack-dev-server \
  && npm i 

EXPOSE 3000
EXPOSE 3035

ENTRYPOINT ["bin/docker-entrypoint"]
CMD ["sleep", "infinity"]