# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

gem "concurrent-ruby", "1.3.4"
gem "decidim", git: "https://github.com/decidim/decidim.git", branch: ENV.fetch("DECIDIM_BRANCH", "release/0.29-stable")
gem "bootsnap", "~> 1.3"
gem "puma", ">= 6.3.1"
gem "wicked_pdf", "~> 2.1"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri
  gem "brakeman", "~> 6.1"
  gem "decidim-dev",   git: "https://github.com/decidim/decidim.git", branch: ENV.fetch("DECIDIM_BRANCH")
  gem "net-imap", "~> 0.2.3"
  gem "net-pop", "~> 0.1.1"
  gem "net-smtp", "~> 0.3.1"
end

group :development do
  gem "letter_opener_web", "~> 2.0"
  gem "listen", "~> 3.1"
  gem "web-console", "~> 4.2"
end

gem "good_job"
gem "dalli"
gem "aws-sdk-s3", require: false
gem "activerecord-postgis-adapter"
gem "concurrent-ruby", "1.3.4"
gem "image_processing", "~> 1.2"

gem "deface", 
  git: "https://github.com/froger/deface",
  branch: "fix/js-overrides"

gem "next_gen_images", 
  git: "https://github.com/froger/next_gen_images", 
  branch: "chore/rails-7.0"

gem "tty-prompt"
gem "opentelemetry-exporter-otlp"
gem "opentelemetry-exporter-otlp-logs"
gem "opentelemetry-instrumentation-all"
gem "opentelemetry-logs-sdk"
gem "opentelemetry-sdk"
gem "deepl-rb"

require File.join(ENV.fetch("ROOT", Dir.pwd), "lib/decidim/voca.rb")
Decidim::Voca.each_gem do |gem_config, gem_attributes|
  gem(*gem_config, **gem_attributes)
end

module_gemfile = ENV.fetch("DECIDIM_MODULE_GEMFILE", "Gemfile.modules")
eval_gemfile module_gemfile if File.exist?(module_gemfile)
