# frozen_string_literal: true

source "https://rubygems.org"

ruby RUBY_VERSION

gem "concurrent-ruby", "1.3.4"
gem "decidim", git: "https://github.com/decidim/decidim.git", branch: "release/0.29-stable"

gem "bootsnap", "~> 1.3"
gem "faker", "~> 3.2"
gem "puma", ">= 6.3.1"
gem "wicked_pdf", "~> 2.1"
gem "deface", git: "https://github.com/froger/deface", branch: "fix/js-overrides"

group :development, :test do
  gem "byebug", "~> 11.0", platform: :mri
  gem "decidim-dev", git: "https://github.com/decidim/decidim.git", branch: "release/0.29-stable"
end

gem "airbrake", "~> 13.0"
gem "dalli"
gem "sidekiq"
gem "image_processing", "~> 1.2"
gem "next_gen_images", git: "https://github.com/froger/next_gen_images", 
    branch: "chore/rails-7.0"

require File.join(ENV.fetch("ROOT"), "lib/decidim/voca.rb")
Decidim::Voca.each_gem do |gem_config, gem_attributes|
  gem(*gem_config, **gem_attributes)
end
